#!/bin/bash

animate_text() {
    text="$1"
    delay="$2"
    for (( i=0; i<${#text}; i++ )); do
        echo -n "${text:$i:1}"
        sleep "$delay"
    done
    echo
}

animate_text "HaadLC - CTF | Fourth Challenge" 0.08

echo -e "\n4. What distinguishes an advanced pentesting lab from the other two options mentioned?"

echo -e "\nPrompt: We named this like flag.txt you can find easily ;) "
