#!/bin/bash

animate_text() {
    text="$1"
    delay="$2"
    for (( i=0; i<${#text}; i++ )); do
        echo -n "${text:$i:1}"
        sleep "$delay"
    done
    echo
}

animate_text "HaadLC - CTF | Fifth Challenge" 0.08

echo -e "\n5. How does Wi-Fi Pineapple from Hak5 aid in pentesting?"

echo -e "\nPrompt: Check your config terminal maybe there your flag ;) "
