#!/bin/bash

animate_text() {
    text="$1"
    delay="$2"
    for (( i=0; i<${#text}; i++ )); do
        echo -n "${text:$i:1}"
        sleep "$delay"
    done
    echo
}

animate_text "HaadLC - CTF | Ninth Challenge" 0.08

echo -e "\n9. Name the author of the book "Penetration Testing: A Hands-on Introduction to Hacking ?"

echo -e "\nPrompt: "
