#!/bin/bash

animate_text() {
    text="$1"
    delay="$2"
    for (( i=0; i<${#text}; i++ )); do
        echo -n "${text:$i:1}"
        sleep "$delay"
    done
    echo
}

animate_text "HaadLC - CTF | Seventh Challenge" 0.08

echo -e "\n7. Briefly explain the significance of system administrator-level skills in Linux and Windows OS?"

echo -e "\nPrompt: "
